name: Auto merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "GitHub Actor: ${{ github.actor }}"
    ã€€- run: echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
      - uses: actions/checkout@v4
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto